apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 859621957271.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 859621957271.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 2103a8b4
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
